AllCops:
  Exclude:
    - db/schema.rb
    - config/unicorn.rb
    - tmp/**/*
    - vendor/bundle/**/*
    - node_modules/**/*
    - bin/*
    - Gemfile
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - lib/**/*
    - config/**/*
    - app/admin/**/*
    - app/services/*
    - lib/tasks/auto_annotate_models.rake

GlobalVars:
  AllowedVariables:
    - $redis
    - $twitter

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# 「and」「or」の使用を許可
AndOr:
  Enabled: false

# Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Lint/StringConversionInInterpolation:
  Exclude:
    - 'spec/steps/**/*_steps.rb'

Style/WordArray:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Style/RaiseArgs:
  EnforcedStyle: compact

# Disable frozen_string_literal required on top of file
Style/FrozenStringLiteralComment:
  Enabled: false
